version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 fileupload:fileupload --reload
    environment:
      - FLASK_APP=fileupload.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "8000:8000"
    volumes:
    - ./:/root