version: "3.7"

services:
  web:
    build: .
    command: python wsgi.py
    ports:
      - 5000:5001
    depends_on:
      - postgres
    restart: on-failure

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cursor
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=cursor_sqlalchemy_db